export default {
  price: 'price',
  orderBookL2_25: 'orderBookL2_25',
  order: 'order',
  wallet: 'wallet',
  position: 'position',
  connectToExchange: 'connectToExchange',
  connectedToExchange: 'connectedToExchange',
  disconnectFromExchange: 'disconnectFromExchange',
  disconnectedFromExchange: 'disconnectedFromExchange',
  checkIsConnected: 'checkIsConnected',
  answerIsConnected: 'answerIsConnected',
  startBot: 'startBot',
  stopBot: 'stopBot',
  checkIsBotStarted: 'checkIsBotStarted',
  answerIsBotStarted: 'answerIsBotStarted',
}
