export default {
    cryptKey: 'Profit_Bot',
    success: 'success',
    error: 'error',
    unknownServerError: 'Unknown server error.',
    emailAlreadyRegistered: 'This email is already registered.',
    usernameAlreadyRegistered: 'This username is already registered.',
    // successfullyRegistered: 'Successfully registered. Please activate your account by validation email.',
    successfullyRegistered: 'Successfully registered. Please try to sign in.',
    emailIsInvalid: 'Your email is invalid',
    usernameIsInvalid: 'Your username is invalid',
    passwordIsInvalid: 'Your password is incorrect',
    yourAccountIsNotAllowed: 'Your account is not allowed. Make sure your account allowed via email validation.',
    verifyFailDueToInvalidToken: 'Sorry! Your account can not be activated. Your token is invalid.',
    verifyFailDueToExpiredToken: 'Sorry! Your account can not be activated. Your token is expired.',
    verifySuccess: 'Your account is successfully activated. Now you can use our website.',
    successfullySignedIn: 'Successfully signed in',
    successfullySignedOut: 'Successfully signed out',
    error404: 'Not Fount',
    error500: 'Unknown server error',
    successfullySaved: 'Successfully saved',
    successfullyChanged: 'Successfully changed',
    successfullyDeleted: 'Successfully deleted',
    successfullyEdited: 'Successfully edited',
    successfullyAdded: 'Successfully added',
    currentPasswordIncorrect: 'Current password is incorrect',
    failedDueToUnknownServerError: 'Failed due to unknown server error',
    invalidParameters: 'Invalid parameters',
    invitationCodeIsInvalid: 'Invitation code is invalid',
    binSizeIsInvalid: 'BinSize is invalid',
    timezoneIsInvalid: 'Timezone is invalid',
    thisEmailIsAlreadyUsed: 'This email is already used',
    symbolIsInvalid: 'Symbol is invalid',
    recalculationIsAlreadyBeingPerformed: 'Recalculation is already being performed',
    successfullyRequested: 'Successfully requested',
    successfullyConnected: 'Successfully connected',
    noBotIsReady: 'No bot is ready',
    successfullyStarted: 'Successfully started',
    successfullyStopped: 'Successfully stopped',
    generalReply: 'General reply',
    botOrder: 'Bot Order',
    apiKeyIsInvalid: 'ApiKey is invalid',
    botIsInvalid: 'Bot is invalid',
    alreadyLongPosition: 'Already Long position',
    alreadyShortPosition: 'Already Short position',
};
